--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniel/nextcloud/Media/Wallpapers/wallpapers/Art/Zdzisław Beksiński/1342985169850.jpg"

-- Special
background="#050403"
foreground="#c2a79c"
cursor="#c2a79c"

-- Colors
color0="#050403"
color1="#76442F"
color2="#764F47"
color3="#945431"
color4="#A45B35"
color5="#9C6134"
color6="#AB6335"
color7="#c2a79c"
color8="#87746d"
color9="#76442F"
color10="#764F47"
color11="#945431"
color12="#A45B35"
color13="#9C6134"
color14="#AB6335"
color15="#c2a79c"
