# Shell variables
# Generated by 'wal'
wallpaper='/home/daniel/nextcloud/Media/Wallpapers/wallpapers/Art/Zdzisław Beksiński/1342985169850.jpg'

# Special
background='#050403'
foreground='#c2a79c'
cursor='#c2a79c'

# Colors
color0='#050403'
color1='#76442F'
color2='#764F47'
color3='#945431'
color4='#A45B35'
color5='#9C6134'
color6='#AB6335'
color7='#c2a79c'
color8='#87746d'
color9='#76442F'
color10='#764F47'
color11='#945431'
color12='#A45B35'
color13='#9C6134'
color14='#AB6335'
color15='#c2a79c'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
