# Shell variables
# Generated by 'wal'
wallpaper='/home/daniel/nextcloud/Media/Wallpapers/eric-jacob-G0miZ5OYaXI-unsplash.jpg'

# Special
background='#2f2e1f'
foreground='#ebe1d0'
cursor='#ebe1d0'

# Colors
color0='#2f2e1f'
color1='#B1B6AD'
color2='#CBB991'
color3='#C5BDA6'
color4='#BDC2BA'
color5='#DBC59C'
color6='#D0C7B0'
color7='#ebe1d0'
color8='#a49d91'
color9='#B1B6AD'
color10='#CBB991'
color11='#C5BDA6'
color12='#BDC2BA'
color13='#DBC59C'
color14='#D0C7B0'
color15='#ebe1d0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
