--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniel/nextcloud/Media/Wallpapers/eric-jacob-G0miZ5OYaXI-unsplash.jpg"

-- Special
background="#2f2e1f"
foreground="#ebe1d0"
cursor="#ebe1d0"

-- Colors
color0="#2f2e1f"
color1="#B1B6AD"
color2="#CBB991"
color3="#C5BDA6"
color4="#BDC2BA"
color5="#DBC59C"
color6="#D0C7B0"
color7="#ebe1d0"
color8="#a49d91"
color9="#B1B6AD"
color10="#CBB991"
color11="#C5BDA6"
color12="#BDC2BA"
color13="#DBC59C"
color14="#D0C7B0"
color15="#ebe1d0"
