# Shell variables
# Generated by 'wal'
wallpaper='/home/daniel/nextcloud/Media/Wallpapers/wallpapers/Vibrant/village.jpg'

# Special
background='#12120d'
foreground='#becdc3'
cursor='#becdc3'

# Colors
color0='#12120d'
color1='#6A8C26'
color2='#DF9E15'
color3='#C5B04E'
color4='#5F6195'
color5='#9353A6'
color6='#759DAE'
color7='#becdc3'
color8='#858f88'
color9='#6A8C26'
color10='#DF9E15'
color11='#C5B04E'
color12='#5F6195'
color13='#9353A6'
color14='#759DAE'
color15='#becdc3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
