--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniel/nextcloud/Media/Wallpapers/wallpapers/Vibrant/village.jpg"

-- Special
background="#12120d"
foreground="#becdc3"
cursor="#becdc3"

-- Colors
color0="#12120d"
color1="#6A8C26"
color2="#DF9E15"
color3="#C5B04E"
color4="#5F6195"
color5="#9353A6"
color6="#759DAE"
color7="#becdc3"
color8="#858f88"
color9="#6A8C26"
color10="#DF9E15"
color11="#C5B04E"
color12="#5F6195"
color13="#9353A6"
color14="#759DAE"
color15="#becdc3"
