--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniel/nextcloud/Media/Wallpapers/wallpapers/Etc/burj.jpg"

-- Special
background="#010016"
foreground="#9ac9d7"
cursor="#9ac9d7"

-- Colors
color0="#010016"
color1="#C43E63"
color2="#E84F66"
color3="#FE6E67"
color4="#FE956A"
color5="#FCDB76"
color6="#23479B"
color7="#9ac9d7"
color8="#6b8c96"
color9="#C43E63"
color10="#E84F66"
color11="#FE6E67"
color12="#FE956A"
color13="#FCDB76"
color14="#23479B"
color15="#9ac9d7"
