--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniel/nextcloud/Media/Wallpapers/WE_ART_CRUSHIFORM_21-1.jpg"

-- Special
background="#090E10"
foreground="#f3e3db"
cursor="#f3e3db"

-- Colors
color0="#090E10"
color1="#4D5961"
color2="#9C8159"
color3="#75929B"
color4="#7D8CA2"
color5="#939CAD"
color6="#EDBFAF"
color7="#f3e3db"
color8="#aa9e99"
color9="#4D5961"
color10="#9C8159"
color11="#75929B"
color12="#7D8CA2"
color13="#939CAD"
color14="#EDBFAF"
color15="#f3e3db"
