# Shell variables
# Generated by 'wal'
wallpaper='/home/daniel/nextcloud/Media/Wallpapers/WE_ART_CRUSHIFORM_21-1.jpg'

# Special
background='#090E10'
foreground='#f3e3db'
cursor='#f3e3db'

# Colors
color0='#090E10'
color1='#4D5961'
color2='#9C8159'
color3='#75929B'
color4='#7D8CA2'
color5='#939CAD'
color6='#EDBFAF'
color7='#f3e3db'
color8='#aa9e99'
color9='#4D5961'
color10='#9C8159'
color11='#75929B'
color12='#7D8CA2'
color13='#939CAD'
color14='#EDBFAF'
color15='#f3e3db'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
