# Shell variables
# Generated by 'wal'
wallpaper='/home/daniel/nextcloud/Media/Wallpapers/chris-lawton-6tfO1M8_gas-unsplash.jpg'

# Special
background='#181c1d'
foreground='#f6eddf'
cursor='#f6eddf'

# Colors
color0='#181c1d'
color1='#7A807E'
color2='#A28B70'
color3='#C6A578'
color4='#A5978B'
color5='#D0B296'
color6='#EBCFB2'
color7='#f6eddf'
color8='#aca59c'
color9='#7A807E'
color10='#A28B70'
color11='#C6A578'
color12='#A5978B'
color13='#D0B296'
color14='#EBCFB2'
color15='#f6eddf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
