--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniel/nextcloud/Media/Wallpapers/chris-lawton-6tfO1M8_gas-unsplash.jpg"

-- Special
background="#181c1d"
foreground="#f6eddf"
cursor="#f6eddf"

-- Colors
color0="#181c1d"
color1="#7A807E"
color2="#A28B70"
color3="#C6A578"
color4="#A5978B"
color5="#D0B296"
color6="#EBCFB2"
color7="#f6eddf"
color8="#aca59c"
color9="#7A807E"
color10="#A28B70"
color11="#C6A578"
color12="#A5978B"
color13="#D0B296"
color14="#EBCFB2"
color15="#f6eddf"
