#!/bin/bash
# run from project root

function apply_dotfiles {
    cp .bashrc.remote ~/.bashrc
    cp .bash_aliases ~/
    cp .bash_profile ~/
    cp .tmux.conf ~/
    cp .vimrc ~/
}

function apply_vim_plugins {
    rm -rf ~/.vim-plugins
    cp -R .vim-plugins/ ~/
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

function apply_scripts {
    mkdir -p ~/.scripts
    cp .scripts/apply_dotfiles_remote ~/.scripts/
    cp .scripts/git2ssh ~/.scripts/
    cp .scripts/set_ssh_banner ~/.scripts/
    chmod +x ~/.scripts/*
}

apply_dotfiles
apply_vim_plugins
apply_scripts
