#!/bin/bash
# script to apply dotfiles on a remote machine

function apply_dotfiles {
    cp ~/.dotfiles/.bashrc.remote ~/.bashrc
    cp ~/.dotfiles/.bash_aliases ~/
    cp ~/.dotfiles/.bash_profile ~/
    cp ~/.dotfiles/.tmux.conf ~/
    cp ~/.dotfiles/.vimrc ~/
}

function apply_vim_plugins {
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

function apply_scripts {
    mkdir -p ~/.scripts
    cp ~/.dotfiles/.scripts/apply_dotfiles_remote ~/.scripts/
    cp ~/.dotfiles/.scripts/git2ssh ~/.scripts/
    cp ~/.dotfiles/.scripts/set_ssh_banner ~/.scripts/
    cp ~/.dotfiles/.scripts/random_banner ~/.scripts/
    cp ~/.dotfiles/.scripts/random_password ~/.scripts/
    chmod +x ~/.scripts/*
}

apply_dotfiles
apply_vim_plugins
apply_scripts
