#!/bin/sh
manual=$(apropos -s ${SECTION:-''} ${@:-.} | \
    grep -v -E '^.+ \(0\)' |\
    awk '{print $2 "    " $1}' | \
    sort | \
    # fzy | \
    dmenu -fn "$DMENU_FONT" -i -l 35 -p "Choose manual"  | \
    sed -E 's/^\((.+)\)/\1/')

[ -z "$manual" ] && exit 0
man -T${FORMAT:-pdf} $manual | ${READER:-zathura -}
