#!/bin/bash
OUT="$2"
if [ -z "$OUT" ]; then
    OUT="/tmp/$(random_string).pdf"
fi

pandoc "$1" \
    -V linkcolor:blue \
    -V geometry:a4paper \
    -V geometry:margin=2cm \
    -f markdown \
    -V mainfont="Roboto" \
    -V monofont="Source Code Pro" \
    --highlight-style="$HOME/.config/pandoc/tango.theme" \
    --pdf-engine=xelatex \
    -H "$HOME/.config/pandoc/header.tex" \
    -o "$OUT" \
    && echo "PDF written to $OUT."

if [ -e "$OUT" ]; then
    read -rp "Open? (Y/n) " ANSWER
    if [ "$ANSWER" = "n" ]; then exit; fi
    rifle "$OUT"
fi
