#!/bin/bash
HDD="$(lsblk -o name,uuid | \
    awk '/53455f48-439c-42da-ba54-a1b366cae044/ { print $1 }' | \
    tr -cd '\11\12\15\40-\176')"
if [ -n "$HDD" ]; then
    sudo cryptsetup open "/dev/$HDD" seagate
    sudo mount /dev/mapper/seagate /mnt/seagate
else
    echo "Seems like the drive is not attached."
fi
