#!/bin/bash

THEME_NAME=$1
if [ ! "$THEME_NAME" ]; then
    printf "Theme name: "
    read -r THEME_NAME
fi

mkdir -p "$HOME/.themes/$THEME_NAME"
cp -R ~/.cache/wal/* "$HOME/.themes/$THEME_NAME/"
cp ~/.fehbg "$HOME/.themes/$THEME_NAME/"
rm -rf "$HOME/.themes/$THEME_NAME/schemes"

