#!/bin/sh

notify-send "RSS" "Updating feeds..." -t 3000
rm "$HOME/.sfeed/feeds/"*
sfeed_update 2>/dev/null

URL=$(sfeed_plain "$HOME/.sfeed/feeds/"* | sort -r | dmenu -l 35 -i | \
	sed -n 's@^.* \([a-zA-Z]*://\)\(.*\)$@\1\2@p')
if [ -n "$URL" ]; then
    # prompt to open youtube links with mpv
    if [ "${URL#*youtube.com}" != "$URL" ]; then
        MPV="$(printf 'No\nYes' | dmenu -i -p 'Open with mpv?')"
        if [ "Yes" = "$MPV" ]; then
            notify-send "YouTube" "Loading video..." -t 3000
            mpv "$URL"
            exit
        fi
    fi
    qutebrowser "$URL"
fi

