#!/bin/sh

SE="$(echo -e "DuckDuckGo\nGoogle\nGitHub\nYouTube\nIMDb\nTorrent (1337x.to)" \
    | dmenu -i -fn "$DMENU_FONT" -p "Select search engine")"
if [ -z "$SE" ]; then
    exit
fi

Q="$(printf "" | dmenu -fn "$DMENU_FONT" -p "Search query")"
if [ -z "$Q" ]; then
    exit
fi
case $SE in
    "DuckDuckGo")
        $BROWSER "https://duckduckgo.com/?q=$Q&ia=web"
        # surf "https://duckduckgo.com/?q=$Q&ia=web"
        ;;
    "Google")
        $BROWSER "https://www.google.com/search?q=$Q"
        # surf "https://www.google.com/search?q=$Q"
        ;;
    "GitHub")
        $BROWSER "https://github.com/search?q=$Q"
        # surf "https://github.com/search?q=$Q"
        ;;
    "YouTube")
        $BROWSER "https://www.youtube.com/results?search_query=$Q"
        ;;
    "IMDb")
        $BROWSER "https://www.imdb.com/find?q=$Q"
        ;;
    "Torrent (1337x.to)")
        $BROWSER "https://1337x.to/search/$Q/1/"
        ;;
esac
