#!/bin/bash
brightness=$(echo -e "10%\n20%\n30%\n40%\n50%\n60%\n70%\n80%\n90%\n100%" | dmenu -i -fn "Misc Tamsyn:pixelsize=17" -p "Display brightness")
case $brightness in
  10%)
    xbacklight -set 10
    ;;
  20%)
    xbacklight -set 20
    ;;
  30%)
    xbacklight -set 30
    ;;
  40%)
    xbacklight -set 40
    ;;
  50%)
    xbacklight -set 50
    ;;
  60%)
    xbacklight -set 60
    ;;
  70%)
    xbacklight -set 70
    ;;
  80%)
    xbacklight -set 80
    ;;
  90%)
    xbacklight -set 90
    ;;
  100%)
    xbacklight -set 100
    ;;
esac
pkill -RTMIN+4 dwmblocks
