#!/bin/bash
HOST=$(grep '^Host' ~/.ssh/config | grep -v '[?*]' | cut -d ' ' -f 2- \
    |dmenu -i -fn "$DMENU_FONT" -p "Choose a server")
if [ -n "$HOST" ]; then
    urxvtc -e "/bin/bash" -c "ssh $HOST"
fi
