#!/bin/bash

# dotfiles
cp ~/.bash_aliases ~/.dotfiles/
cp ~/.bash_profile ~/.dotfiles/
cp ~/.bashrc ~/.dotfiles/
cp ~/.spacemacs ~/.dotfiles/
cp ~/.tmux.conf ~/.dotfiles/
cp ~/.vimrc ~/.dotfiles/
cp ~/.xinitrc ~/.dotfiles/
cp ~/.Xresources ~/.dotfiles/
rm -rf ~/.dotfiles/.Xresources.d
cp -R ~/.Xresources.d ~/.dotfiles/.Xresources.d

# /usr/local/bin
mkdir -p ~/.dotfiles/usr/local/bin
cp /usr/local/bin/dwm_* ~/.dotfiles/usr/local/bin

# dwmblocks config
cp ~/projects/suckless/dwmblocks/config.h ~/.dotfiles/dwmblocks_config.h

# .dwm directory
mkdir -p ~/.dotfiles/.dwm
cp ~/.dwm/autostart_blocking.sh ~/.dotfiles/.dwm
cp ~/.dwm/autostart.sh ~/.dotfiles/.dwm/

# .scripts directory
mkdir -p ~/.dotfiles/.scripts
cp ~/.scripts/* ~/.dotfiles/.scripts/

# my themes
rm -rf ~/.dotfiles/.themes
cp -R ~/.themes ~/.dotfiles/

# dunst
mkdir -p ~/.dotfiles/.config/dunst
cp ~/.config/dunst/dunstrc ~/.dotfiles/.config/dunst/

# ranger
mkdir -p ~/.dotfiles/.config/ranger
cp ~/.config/ranger/rc.conf ~/.dotfiles/.config/ranger/
cp ~/.config/ranger/rifle.conf ~/.dotfiles/.config/ranger/

# sxhkd
mkdir -p ~/.dotfiles/.config/sxhkd
cp ~/.config/sxhkd/sxhkdrc ~/.dotfiles/.config/sxhkd/

# qutebrowser
mkdir -p ~/.dotfiles/.config/qutebrowser
cp ~/.config/qutebrowser/config.py ~/.dotfiles/.config/qutebrowser

# pandoc
mkdir -p ~/.dotfiles/.config/pandoc
cp ~/.config/pandoc/* ~/.dotfiles/.config/pandoc

