#!/bin/bash

RATE=$(curl https://transferwise.com/us/currency-converter/eur-to-usd-rate 2>/dev/null | \
    grep "text-success" | \
    cut -d'>' -f 2 | cut -d'<' -f 1 | \
    tail -1
)

EUR=$(printf %.2f "$(echo "$1 / $RATE" | bc -l)")
echo "USD: $1"
echo "EUR: $EUR"
