--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniel/nextcloud/Media/Wallpapers/reflection-of-trees-on-water-2563129.jpg"

-- Special
background="#0c0a09"
foreground="#f4e4cc"
cursor="#f4e4cc"

-- Colors
color0="#0c0a09"
color1="#8B766C"
color2="#AF8F76"
color3="#466383"
color4="#847D85"
color5="#A3928D"
color6="#D5AF95"
color7="#f4e4cc"
color8="#aa9f8e"
color9="#8B766C"
color10="#AF8F76"
color11="#466383"
color12="#847D85"
color13="#A3928D"
color14="#D5AF95"
color15="#f4e4cc"
