# Shell variables
# Generated by 'wal'
wallpaper='/home/daniel/nextcloud/Media/Wallpapers/reflection-of-trees-on-water-2563129.jpg'

# Special
background='#0c0a09'
foreground='#f4e4cc'
cursor='#f4e4cc'

# Colors
color0='#0c0a09'
color1='#8B766C'
color2='#AF8F76'
color3='#466383'
color4='#847D85'
color5='#A3928D'
color6='#D5AF95'
color7='#f4e4cc'
color8='#aa9f8e'
color9='#8B766C'
color10='#AF8F76'
color11='#466383'
color12='#847D85'
color13='#A3928D'
color14='#D5AF95'
color15='#f4e4cc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
